### ISSUE TITLE
answer with extra words

### ISSUE THREAD

**Issue by Sylvamy** [abcboy101/discordtrivia#2]
Is there anyway to make it so the bot scans the message for the correct answer? so people could answer in weird ways
example:
What is the capital city of England?*London

user types: well its london obviously
correct answer

**Comment by abcboy101** [comment]
I've added a `containsAnswer` setting in 4cedab8 that you can set to `true` to allow for this. I've set the default to `false` though, since with this setting it will accept things like "unknown" for "known" or "Washington, D.C." for "Washington" since they contain the correct answer as a substring despite being wrong.

**Comment by Sylvamy** [comment]
Hi, i think maybe you made an error? when enabled ANYTHING that gets typed is the correct answer
https://i.imgur.com/HzZi9VX.png

**Comment by abcboy101** [comment]
Okay, 24ef1ff should actually work now
